import React from "react";
import SiderBarAdminPage from "@/components/siderbarAdminPage";
import { Inter } from "next/font/google";
import "./admin.module.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Adminstator",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex justify-center items-center">
            <SiderBarAdminPage />
            <div className="container ml-0 sm:ml-[270px] ">
                {children}
            </div>
        </div>
    </body>
    </html>
  );
}
